apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-volume
  namespace: ahem
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
